### ISSUE TITLE
Is it currently possible to mock methods in R6 classes?

### ISSUE THREAD

**Issue by nachocab** [hadley/testthat#330] opened 2015-12-04 19:55 UTC
@krlmlr I don't think it's currently possible, but I'm wondering if there is a workaround. This is what it would look like:

    MyClass <- R6Class("MyClass",
        public = list(
            initialize = function(){
                print(self$add_xy(2,3))
            },
            add_xy = function(x,y){
                x + y
            }
        )
    )

    # currently fails
    test_that("add_xy", with_mock(
        MyClass$add_xy = function(x,y) {TRUE}, 
        expect_true(MyClass$new())
    ))

**Comment by hadley** [comment] 2015-12-05 05:44
Duplicate of #329

**Closed by hadley** 2015-12-05 05:44 UTC
