### ISSUE TITLE
Uncounted tests: testthat results === OK: 0 SKIPPED: 0 FAILED: 0

### ISSUE THREAD

**Issue by cbare** [hadley/testthat#477] opened 2016-05-19 18:41 UTC
Many thanks for testthat!

Sometimes after completing many tests, I get output like the following:
```
... lots of tests pass ...
Error: `medianF0s` not equal to `expected_medianF0s`.
2/3 mismatches (average diff: 71.2)
[2] 107 - 178 == -71.2
[3] 178 - 107 ==  71.2
[... snip ...]
No traceback available 
testthat results ================================================================
OK: 0 SKIPPED: 0 FAILED: 0
```
I expected to see some OK's and FAILED: 1.

A little googling shows similar output for a few CRAN packages, such as:
```
CRAN Package Check Results for Package dtwSat
Last updated on 2016-05-19 19:47:55.
[... snip ...]
Version: 0.1.0 
Check: tests 
Result: ERROR 
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
     1 1 2011-10-04 2012-02-07 2.580247 0.02389117 FALSE
     2 1 2009-09-28 2010-03-05 2.795275 0.02588217 FALSE
     3 1 2010-10-20 2011-01-31 2.850574 0.02639421 FALSE
     4 1 2012-09-14 2013-02-15 3.056848 0.02830414 FALSE
     Time-Weighted DTW alignment object
     Number of alignments: 4 
     query from to distance normalizedDistance stringsAsFactors
     1 1 2011-10-04 2012-02-07 2.580247 0.02389117 FALSE
     2 1 2009-09-28 2010-03-05 2.795275 0.02588217 FALSE
     3 1 2010-10-20 2011-01-31 2.850574 0.02639421 FALSE
     4 1 2012-09-14 2013-02-15 3.056848 0.02830414 FALSE
     Error: `breaks` and `labels` must have the same length
     testthat results ================================================================
     OK: 0 SKIPPED: 0 FAILED: 0
     Execution halted 
Flavors: r-devel-linux-x86_64-debian-gcc, r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, r-devel-osx-x86_64-clang
```

**Comment by kevinushey** [comment] 2016-05-27 22:38
Do these tests live within a `test_that` block, or are they standalone checks within a file?

**Comment by cbare** [comment] 2016-06-02 18:44
Aha, maybe we're using the tool wrong. We didn't enclose tests in test_that(...), rather we just used expect_true and expect_equal, for [example](https://github.com/Sage-Bionetworks/mPowerProcessing/blob/master/tests/testthat/test_220_unit_process_voice_activity.R). Is that the reason for the zero counts? It's counting test_that blocks? Thanks!

**Comment by kevinushey** [comment] 2016-06-02 20:01
For what it's worth, this behavior changed with the latest release of `testthat` (I believe this worked fine in older versions) -- you can work around it by explicitly enclosing the checks within `test_that` blocks and I think this is preferred; but this may be fixed in a later release.

**Comment by cbare** [comment] 2016-06-02 20:05
Thanks for the info. Feel free to close, if that's most appropriate.

**Comment by krlmlr** [comment] 2016-06-25 01:12
@cbare: As @kevinushey said, the tests are counted only if they live in a test_that() block, one per expectation (expect_...() function). Closing for now, I don't think this is going to change any time soon.

**Closed by krlmlr** 2016-06-25 01:12 UTC

**Comment by krlmlr** [comment] 2016-06-25 01:21
Actually, this is a duplicate of #427.
