### ISSUE TITLE
option to signal warnings and messages

### ISSUE THREAD

**Issue by gagolews** [hadley/testthat#276] opened 2015-07-05 12:51 UTC
Since the resolution of #189, warnings and messages are totally ignored while being generated within `test_that(...)`. I reckon that this is useful for some, but this might not be the best idea for all.

The current logic behind ignoring warnings is quite invasive, `options(warn=2)` does not cause warnings to be turned into errors. I guess that some option (perhaps via `options(testthat_warnings=TRUE)` or something?) to turn the "old behavior" on could be helpful.

**Comment by brodieG** [comment] 2015-08-27 01:34
Agreed.  I would propose a `verbose` parameter to `test_file` or `test_dir`.  I'm trying to debug some tests that run fine normally, but freak out when run under `covr` and this would be super helpful since I can't rely on the usual `debug` / `browser` approaches.

**Comment by hadley** [comment] 2015-09-24 13:59
Hmmm, I think that ignoring messages is the right thing to do (in the same way printed output is ignored), but ignoring warnings might be too much. I definitely don't think a global option is the right thing to do.

**Comment by hadley** [comment] 2015-09-24 14:53
Duplicate of #254

**Closed by hadley** 2015-09-24 14:53 UTC
