### ISSUE TITLE
test_check fails if expect_more_than/expect_less_than have vector arguments

### ISSUE THREAD

**Issue by cdiener** [hadley/testthat#286] opened 2015-08-07 19:53 UTC
Hi, 

since version 0.10 all my devtools::check() runs fail due to an error in test_check when assembling the test_results. It is due to an issue between expect_more_than/expect_less_than with vector arguments and test_check.

Minimal example (with devtools):

```R
devtools::create("abc")
devtools::use_testthat("abc")
write("test_that('bla', expect_more_than(1:3,0))", file="abc/tests/testthat/test_err.R")
devtools::test("abc")
devtools::check("abc")
```

This can also be reproduced with test_file/test_dir (suceeds) and test_package/test_check (error).

I think it would be good if the behaviour is consistent, meaning that if vector comparisons are not supposed to be used in the expect_* functions they should always cause a test fail and not only in some instances.

**Comment by hadley** [comment] 2015-09-24 13:47
Duplicate of #279

**Closed by hadley** 2015-09-24 13:47 UTC
